# Generated by Django 4.2 on 2024-05-05 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio_evaluado2app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccion',
            old_name='dpto',
            new_name='departamento',
        ),
    ]
